install.packages("reticulate")
library(reticulate)
install_miniconda(path = "C:/Users/msalas/miniconda",update = TRUE)
miniconda_path()
options(reticulate.conda_binary = "C:/Users/msalas/miniconda/")
conda_list(conda = "C:/Users/msalas/AppData/Local/r-miniconda")
use_condaenv(condaenv = "r-reticulate",conda ="C:/Users/msalas/miniconda/_conda.exe")
Sys.which("conda")
conda_list()
